sadanandpai/frontend-mini-challenges

react/src/components/challenge/Challenge.tsx
react/src/helpers/challenges.ts
react/src/machine-coding/Guess-the-number/App.jsx
react/src/machine-coding/Guess-the-number/Guess.css

Created Guess-No Feature with a Start button to reset the check while clicking on the check button to find whether your guess is correct or not until your guess is right.

Guess-No Feature Added

---

native/helpers/challenges.js
native/mc/drag-and-drop-puzzle/index.html
native/mc/drag-and-drop-puzzle/index.js
native/mc/drag-and-drop-puzzle/style.css
package-lock.json

added drag-and-drop-puzzle

---

react/package-lock.json
react/package.json
react/src/components/challenge/Challenge.tsx
react/src/helpers/challenges.ts
react/src/machine-coding/todo-list/todo.jsx
react/src/machine-coding/todo-list/todo.module.scss

Todo-List Feature Added

---

react/src/machine-coding/counter/counter.tsx

Issues:
The render method on the React Counter doesn't follow a11y guidelines
Fix: 
Use semantic HTML elements: Replace the <div> elements with appropriate semantic elements to improve the document structure and accessibility.
```
<section>
<button onClick={decrement}>-</button>
<button onClick={increment}>+</button>
</section>
```
Provide alternative text for buttons: Add descriptive text to the buttons so that screen readers can announce their purpose.
```
<section>
<button onClick={decrement} aria-label="Decrement">-</button>
<button onClick={increment} aria-label="Increment">+</button>
</section>
```
Add a title attribute for the input field: Include a descriptive title for the input field to provide additional context.
```
<input
type="number"
id="step"
defaultValue={step.current} …
```

Added accessibility and typo issue fix on React counter package

---

native/helpers/challenges.js
native/machine-coding/lift-simulation/index.html
native/machine-coding/lift-simulation/main.css
native/machine-coding/lift-simulation/main.js

This pull request introduces a JavaScript lift simulation, enabling interactive and dynamic representation of elevator movements within a simulated building. The goal is to improve user understanding of lift operations and enhance real-world applications.

Added: Lift simulation

---

native/machine-coding/password-generator/index.html
native/machine-coding/password-generator/index.js
native/machine-coding/password-generator/style.css

The `rememberPassword` function takes a string `pass` as a parameter and converts it into a memorable phrase by mapping each character to a corresponding word from `ALPHABETWORDS` array. If a character is found in the `ALPHABETWORDS` object, it replaces the character with the corresponding word, otherwise, it appends the character as is. The resulting memorable phrase is returned after trimming any leading or trailing whitespace.

Add rememberPassword function and some style changes

---

.github/workflows/webpack.yml
angular/package.json
angular/src/main.ts

I tried to test whether it works or not on forked repository
Verified below URL's with refresh, both worked fine 
1. https://pankajparkar.github.io/frontend-mini-challenges/angular/
2. https://pankajparkar.github.io/frontend-mini-challenges/angular/machine-coding/counter

Fix angular html5routing issue

---

react/src/helpers/challenges.ts
react/src/machine-coding/food-recipe/App.jsx
react/src/machine-coding/food-recipe/Dialog.jsx
react/src/machine-coding/food-recipe/Food.jsx
react/src/machine-coding/food-recipe/Food.module.css
react/src/machine-coding/food-recipe/Table.jsx
react/src/machine-coding/food-recipe/TagsList.jsx
react/src/pages/Challenge.tsx

Food-recipe React app is a simple food discovery application that fetches a random meal from themealdb API and displays it on the screen. The user can click on the "Another food curry" button to fetch and display a new random food. Additionally, the app allows the user to view more details about the food by clicking on it, which opens a dialog box with additional information about the selected food.

Add new challenge: food-recipe

---

react/src/machine-coding/todo-list/list.jsx
react/src/machine-coding/todo-list/todo.jsx
react/src/machine-coding/todo-list/todo.module.scss

[here is the preview](https://www.loom.com/share/3ffce56000e6435390b9e7132d3b4f9b?sid=492862c7-b176-4e68-9a49-8be6f9e32f96)
I added complete indicator to finished task,

added ability to mark completed task

---

native/helpers/challenges.js
native/machine-coding/navigation-bar/index.html
native/machine-coding/navigation-bar/index.js
native/machine-coding/navigation-bar/style.css

This adds a basic navigation-bar to the JS challenges

add navigation-bar

---

react/src/helpers/challenges.ts
react/src/machine-coding/25-5-clock/Style.module.css
react/src/machine-coding/25-5-clock/index.jsx
react/src/pages/Challenge.tsx

feat: added 25-5 Clock on react section

---

native/helpers/challenges.js
native/machine-coding/snake-game/index.html
native/machine-coding/snake-game/script.js
native/machine-coding/snake-game/style.css

Snake Game is a classic and addictive web-based game that puts players in control of a hungry snake, challenging them to grow as long as possible by eating food scattered across the game board. The objective is to collect as much food as possible and avoid colliding with the walls or the snake's own body. With simple arrow key controls or on-screen buttons, players can steer the snake in different directions and test their skills in this exciting and challenging adventure.

add snake game

---

native/machine-coding/quiz-app/script.js

fix issue by reading null properties 'value' in quiz app

fix cannot read properties of null(reading 'value') in quiz app

---

react/src/components/testimonials/testimonialData.ts

Changes for spelling correction on  Testimonials.

spelling correction on testimonial

---

native/helpers/challenges.js
native/machine-coding/bill-spill/index.html
native/machine-coding/bill-spill/script.js
native/machine-coding/bill-spill/style.css

add new project. Project Name- bill-spill. 
Bill Spill is a web application that makes splitting bills among a group of people hassle-free. With just a few inputs, users can quickly calculate individual shares, including tips, and get a clear overview of the bill distribution.

add new project

---

native/machine-coding/light-dark-mode/style.css

fix: light-dark-mode navbar gradient and icon color

---

native/machine-coding/bill-spill/style.css

add responsive design and improve style

improve style

---

react/src/machine-coding/guess-number/App.jsx

Fixes issue #74 
- Improve the standards and quality of the code "Variable names"
- Improve the "Code quality (functions can be refactored)"
- Add the "Comments" in the code for easy understanding

Fix issue #74

---

native/machine-coding/accordion/index.html
native/machine-coding/accordion/index.js
native/machine-coding/accordion/style.css

Fixes #75 
Demo:
https://github.com/sadanandpai/frontend-mini-challenges/assets/70846516/533c8aa1-ad56-4cb3-8694-22c6cfd8f77e

improvements:accordion

---

CONTRIBUTING.md
vue/src/routes.ts

The imports were failing due to dynamic imports. I've replaced them with static imports in this PR.

Fix VueJs page

---

native/machine-coding/brick-breaker/script.js
native/machine-coding/brick-breaker/styles.css

I have fixed the responsiveness issue #90 in Brick Breaker Game..sorry for any inconveniences caused.
I have:
- Made Play Area Fit the Screen
- Made the Paddle respond to touch in touch screens!
Kindly review this PR under hacktoberfest 2023 if possible. 😊

Made Brick Breaker Game Responsive!

---

react/src/helpers/challenges.ts
react/src/machine-coding/bmi-calculator/App.jsx
react/src/machine-coding/bmi-calculator/BMI.module.scss
react/src/machine-coding/bmi-calculator/BMICalculator.jsx
react/src/machine-coding/bmi-calculator/BMICard.jsx
react/src/pages/Challenge.tsx

I have incorporated a BMI Calculator using React and SCSS into the project. 
Additionally, I have taken care to adhere to the instructions outlined in the Contribution Guide. 
As a newcomer to the world of open source, I would greatly appreciate your guidance and correction if any errors have been made. 
I kindly request that you review this Pull Request as part of HackOctoberfest '23. 
Thank you for your consideration.
Screenshot of BMI Calculator
With inputs

Added a BMI Calculator React Challenge

---

.github/ISSUE_TEMPLATE/add-new-project.md
.github/ISSUE_TEMPLATE/bug_report.md
.github/ISSUE_TEMPLATE/feature_request.md
.github/pull_request_template.md

I have added PR and ISSUE templates for this repository for a better contributing experience!
Kindly review this PR whenever you get the time! Thanks.
Issue:
PR:

Added PR & ISSUE Templates

---

react/src/machine-coding/column-table/Size.tsx

Title : added the count of rows and column for better visualization of the matrix
Issue No. :
Code Stack : 

added the count of rows and column for better visualization of the matrix

---

native/helpers/challenges.js
native/machine-coding/sorting-visualizer/README.md
native/machine-coding/sorting-visualizer/index.html
native/machine-coding/sorting-visualizer/script.js
native/machine-coding/sorting-visualizer/style.css

Title : Sorting visualizer
Issue No. :#110
Code Stack : HTML, CSS and JS
Close #110

Sorting visualizer

---

react/package-lock.json
react/package.json
react/src/helpers/challenges.ts
react/src/helpers/contributors.ts
react/src/machine-coding/qr-code-generator/App.jsx
react/src/machine-coding/qr-code-generator/QRCodeGenerator.jsx
react/src/machine-coding/qr-code-generator/QRCodeGenerator.module.css
react/src/pages/Challenge.tsx

Title :
Issue No. : 98 
Code Stack : Reactjs
Close #98

qr code generator reactjs challenge added

---

react/src/components/features/features.tsx

Title :
Issue No. :
Code Stack : 

Spelling corrected

---

vue/src/helpers/challenges.ts
vue/src/machine-coding/counter/index.vue
vue/src/machine-coding/guess-the-number/index.vue
vue/src/machine-coding/light-dark-mode/index.vue
vue/src/machine-coding/pagination/index.vue
vue/src/machine-coding/table-colorizer/index.vue
vue/src/machine-coding/telephone-formatter/index.vue
vue/src/routes.ts

Added solutions for:
- Telephone formatter
- Light dark mode
- Guess the number
- Table colorizer
- Pagination
Could you please merge it under hacktoberfest

[Vue]: Added few solutions

---

vue/src/helpers/challenges.ts
vue/src/machine-coding/accordion/Accordion.vue
vue/src/machine-coding/accordion/AccordionGroup.vue
vue/src/machine-coding/accordion/data.ts
vue/src/machine-coding/accordion/index.vue
vue/src/routes.ts

Title : Accordion solution for VueJs
Issue No. : none
Code Stack : VueJs
Close #<issue_no> None

[Vue]: Solution for accordion

---

react/src/helpers/challenges.ts
react/src/helpers/contributors.ts
react/src/machine-coding/quote-generator/App.tsx
react/src/machine-coding/quote-generator/README.md
react/src/machine-coding/quote-generator/quote.module.css
react/src/pages/Challenge.tsx

Title :Quote Generator
Issue No. :#116
Code Stack : React, Typescript, CSS
Close #116

Added Quote generator

---

react/src/components/footer/footer.module.scss

Title #118 
Issue No. :#118
Code Stack : css
Close #118 

modified footer

---

react/src/machine-coding/table-colorizer/table-colorizer.module.css

Title :
Issue No. :
Code Stack : 

changes in react table-colorizer ..button should have cursor as pointer

---

react/src/helpers/challenges.ts
react/src/machine-coding/word-count/index.jsx
react/src/machine-coding/word-count/styles.module.css
react/src/pages/Challenge.tsx

Title :
Issue No. :#146
Code Stack : ReactJS
Close #146

Word count is added

---

react/src/machine-coding/stack-implementation/Stack.jsx
react/src/machine-coding/stack-implementation/stack.module.css
react/src/machine-coding/table-colorizer/table-colorizer.module.css

#158
Title : Fixed the issue 158 
Issue No. :
Code Stack : 

[React]: Fixed stack implementation bugs - closes #158

---

native/helpers/challenges.js
native/machine-coding/blobmaker/app.js
native/machine-coding/blobmaker/index.html
native/machine-coding/blobmaker/style.css

 Blob Maker

---

native/helpers/challenges.js
native/machine-coding/currency-converter/README.md
native/machine-coding/currency-converter/index.html
native/machine-coding/currency-converter/script.js
native/machine-coding/currency-converter/style.css

Title :currency-converter
Issue No. :#183
Code Stack : html,css ,javascript
Close #183

Added currency converter

---

react/src/helpers/challenges.ts
react/src/helpers/contributors.ts
react/src/machine-coding/temperature-converter/index.jsx
react/src/machine-coding/temperature-converter/styles.module.css
react/src/pages/Challenge.tsx

Title : Temperature Converter
Issue No. :#223
Code Stack : 
Close #223

temperature converter is added

---

angular/src/app/helpers/challenges.ts
angular/src/app/machine-coding/stack/stack.component.html
angular/src/app/machine-coding/stack/stack.component.scss
angular/src/app/machine-coding/stack/stack.component.ts
angular/src/app/machine-coding/tic-tac-toe/square/square.component.html
angular/src/app/machine-coding/tic-tac-toe/square/square.component.scss
angular/src/app/machine-coding/tic-tac-toe/square/square.component.ts
angular/src/app/machine-coding/tic-tac-toe/tic-tac-toe/tic-tac-toe.component.html
angular/src/app/machine-coding/tic-tac-toe/tic-tac-toe/tic-tac-toe.component.scss
angular/src/app/machine-coding/tic-tac-toe/tic-tac-toe/tic-tac-toe.component.ts
angular/src/app/routes.ts

Title : Add stack and tic tac toe assignment
Code Stack : angular
Home Page
Stack 
Tic Tac Toe

Add stack and tic tac toe assignment

---

angular/src/app/helpers/challenges.ts
angular/src/app/machine-coding/tic-tac-toe/tic-tac-toe/tic-tac-toe.component.ts
angular/src/app/machine-coding/word-count/word-count.component.html
angular/src/app/machine-coding/word-count/word-count.component.scss
angular/src/app/machine-coding/word-count/word-count.component.ts
angular/src/app/routes.ts

Title : Add word count assignment
Code Stack : angular
Home Page
Char count app

Add word count assignment

---

angular/src/app/routes.ts

Title : Todolist app link was broken
Fixed Screenshot

Fix todo list app broken link

---

native/machine-coding/bill-spilt/index.html
native/machine-coding/bill-spilt/style.css

Title :Bill split CSS issue (native JS) #235
Issue No. :#235
Code Stack : 
Close #<issue_no>#235

Bill split CSS issue (native JS) #235

---

native/helpers/contributors.js

Title : Broken Logo and name for Finance tracker & Currency Converter
Issue No. : #216 
ScreenShot : 
Close #216

[JS] Fix broken logo and name - closes #216

---

react/src/machine-coding/todo-list/todo.jsx

The code which I wrote maintains the same functionality but is more structured and reduces the number of lines by using functional updates and a concise map function to update the state.

modified todo.jsx

---

native/helpers/challenges.js
native/machine-coding/word-counter/index.css
native/machine-coding/word-counter/index.html
native/machine-coding/word-counter/index.js

Title :word-counter
Issue No. :#271
Code Stack : HTML, CSS, JAVASCRIPT
Close #271

Added Word Counter

---

native/helpers/challenges.js
native/helpers/contributors.js
native/machine-coding/spinning-loader/index.html
native/machine-coding/spinning-loader/styles.css

Title : Spinning Loader
Issue No. :https://github.com/sadanandpai/frontend-mini-challenges/issues/300
Code Stack : html, css
Close [#<issue_no>](https://github.com/sadanandpai/frontend-mini-challenges/issues/300)

Adding spinning loader

---

react/src/helpers/challenges.ts
react/src/machine-coding/otp/App.jsx
react/src/machine-coding/otp/otp.module.css
react/src/pages/Challenge.tsx

Title : React Otp Challenge
Issue No. :
Code Stack : React JS

ReactOtp Challenge

---

react/src/helpers/challenges.ts
react/src/machine-coding/traffic-light/App.jsx
react/src/machine-coding/traffic-light/config.jsx
react/src/machine-coding/traffic-light/trafficlight.module.css
react/src/pages/Challenge.tsx

Title : TrafficLightChallenge
Issue No. :
Code Stack :  React JS

[React] Add Traffic Light challenge

---

native/helpers/challenges.js
native/helpers/contributors.js
native/machine-coding/bmi-calculator/index.html
native/machine-coding/bmi-calculator/script.js
native/machine-coding/bmi-calculator/styles.css

Title :[Add a BMI calculator]
Issue No. : #159 
Code Stack : html,css, javascript

[JS] Add a BMI calculator - closes #159

---

react/src/components/contribution/contributors.ts
react/src/machine-coding/table-colorizer/TableColorizer.jsx
react/src/machine-coding/table-colorizer/table-colorizer.module.css

Title : Fix (React/Table Colorizer) invalid input handling logic.
Issue No. : #336
Close #336 
- No additional changes to the styles (except for introduction of a style rule for the error text message) have been made.
- Some refactoring/fixing has been done to the `Clear Me` button enable proper functioning of error text message.

fix(React/Table Colorizer): display proper error message. fixes #336

---

react/src/helpers/challenges.ts
react/src/helpers/contributors.ts
react/src/machine-coding/quiz-app/App.tsx
react/src/machine-coding/quiz-app/Quiz.tsx
react/src/machine-coding/quiz-app/Result.tsx
react/src/machine-coding/quiz-app/quiz.module.scss
react/src/machine-coding/quiz-app/react-quiz.json
react/src/machine-coding/quiz-app/types.ts
react/src/machine-coding/quiz-app/utils.ts
react/src/pages/Challenge.tsx

added quiz app challenge
-> Challenge category: React

Quiz application

---

react/src/components/leaderboard/LeaderBoard.tsx
react/src/components/leaderboard/LeaderBoardTable.tsx
react/src/components/leaderboard/leaderboard.module.scss
react/src/helpers/challenges.ts
react/src/helpers/contributors.ts
react/src/helpers/leaderboard.ts
react/src/pages/Home.tsx

Title: Implemented Helper Function for Generating Leaderboard Data
Description:
Added a new helper function, generateLeaderboardData(), designed for creating leaderboard data
Code Changes:
- Created a new file for leaderboard in helpers folder and in component folder
- Included the generateLeaderboardData() function within the leaderboard file located in the helpers folder
- exported Challenge interface and Contributor interface from challenges and contributors file located in the helpers module 
to use it in leaderboard file
- Included Leaderboard in home.jsx

implemented helper function for generating leaderboard data

---

react/src/helpers/challenges.ts
react/src/machine-coding/chess-board/App.tsx
react/src/machine-coding/chess-board/ChessBoard.tsx
react/src/machine-coding/chess-board/chess-board.module.scss
react/src/machine-coding/chess-board/utils.ts
react/src/pages/Challenge.tsx

chess board challenge

---

CODE_OF_CONDUCT.md

Title : change in spelling for code of conduct script( first ever contribution)
Issue No. :
Code Stack : 

fix in code of conduct

---

native/machine-coding/dice-game/dice.js
native/machine-coding/dice-game/index.html
native/machine-coding/dice-game/styles.css

Title :added a button on dice-game project for new game instead of refreshing the page
Issue No. :343
Code Stack : html/css/javascript
Close #343

[JS/dice-game] Add a button for new game

---

apps/react/src/challenges/nested-dropdown/App.jsx
apps/react/src/challenges/nested-dropdown/Dropdown.jsx
apps/react/src/challenges/nested-dropdown/DropdownItems.jsx
apps/react/src/challenges/nested-dropdown/data/data.js
apps/react/src/challenges/nested-dropdown/style.module.css
apps/react/src/helpers/challenges.ts
apps/react/src/helpers/contributors.ts
apps/react/src/pages/Challenge.tsx

**Nested dropdown challenge: React**

nested dropdown challenge

---

apps/vue/src/challenges/password-strength/index.vue
apps/vue/src/helpers/challenges.ts
apps/vue/src/helpers/contributors.ts
apps/vue/src/routes.ts

Title : [Vue]: Add solution for password-strength
Issue No. : [349](https://github.com/sadanandpai/frontend-mini-challenges/issues/349)
Code Stack : VueJs
Close #349

[vue]: add solution for password-strength

---

apps/vue/src/challenges/stack/index.vue
apps/vue/src/helpers/challenges.ts
apps/vue/src/routes.ts
apps/vue/tsconfig.json

Title :  [Vue]: Add solution for stack
Issue No. : [351](https://github.com/sadanandpai/frontend-mini-challenges/issues/351)
Code Stack : VueJs
Close #351

[vue] added solution for stack

---

apps/host/src/components/leaderboard/leaderboard.module.css
apps/host/src/components/leaderboard/leaderboard.tsx
apps/host/src/pages/home.tsx
apps/host/src/pages/leaderboard.ts

Title :
Issue No. :
Code Stack : 

Add: Leader board initial commit

---

apps/react/src/challenges/quote-generator/App.tsx
apps/react/src/challenges/quote-generator/quote.module.css

Added customized loader in the quote-generator react challenge using CSS

Added customized loader

---

.npmrc
apps/angular/src/app/components/challenge-container/challenge-container.component.ts
apps/angular/src/app/components/challenge/challenge.component.ts
apps/angular/src/app/components/challenges/challenges.component.ts
apps/angular/src/app/models/challenge.model.ts
apps/host/package.json
apps/host/src/components/leaderboard/leaderboard.tsx
apps/host/src/helpers/generate-leaderboard.ts
apps/host/src/main.tsx
apps/host/src/pages/home.tsx
apps/host/src/pages/leaderboard.tsx
apps/javascript/index.ts
apps/javascript/package.json
apps/javascript/src/helpers/header.js
apps/javascript/src/helpers/navbar.ts
apps/javascript/vite.config.ts
apps/react/package.json
apps/react/src/components/challenges/ChallengeGrid.tsx
apps/react/src/pages/Challenge.tsx
apps/vue/src/pages/challenge.vue
apps/vue/src/pages/challenges.vue
package-lock.json
shared/data/content/contributors.ts
shared/data/content/index.ts
shared/data/content/js-challenges.ts
shared/data/content/ng-challenges.ts
shared/data/content/react-challenges.ts
shared/data/content/vue-challenges.ts
shared/data/types/challenge.ts

Leaderboard

---

apps/vue/src/challenges/stack/index.vue

Title : [Vue]: Added stack clear-all functionality
Issue No. : 
Code Stack : VueJs

[vue]: added stack clear all functionality

---

apps/vue/src/challenges/password-generator/index.vue
apps/vue/src/routes.ts
shared/data/content/contributors.ts
shared/data/content/vue-challenges.ts

Title : [Vue]:added password-generator solution
Code Stack : Vue

[Vue]:added password-generator solution

---

apps/react/src/challenges/progressbar/ProgressBar.module.css

#[React] Progress-bar challenge is not responsive #199
Title : [React] Progress-bar challenge is not responsive
Issue No. : #199
Code Stack : REACT
Close #199 

[React] Fixed progress bar responsiveness

---

apps/react/src/challenges/anagram-checker/Anagramchecker.jsx
apps/react/src/challenges/anagram-checker/App.jsx
apps/react/src/challenges/anagram-checker/App.module.css
apps/react/src/pages/Challenge.tsx
shared/data/content/contributors.ts
shared/data/content/react-challenges.ts

Title :Adding Anagram Chcker
Issue No. #363 
Close #363

[React]:Adding Anagram checker

---

apps/host/src/components/leaderboard/leaderboard.module.css
apps/host/src/components/leaderboard/leaderboard.tsx
apps/host/src/components/leaderboard/userprofile.tsx
apps/host/src/helpers/generate-leaderboard.ts
apps/host/src/main.tsx
shared/data/types/challenge.ts

Title :
Issue No. :
Code Stack : 

Add: user profile initial commit

---

apps/react/src/challenges/calculator/App.jsx
apps/react/src/challenges/calculator/calculator.module.css
apps/react/src/challenges/calculator/module.css
apps/react/src/pages/Challenge.tsx
shared/data/content/contributors.ts
shared/data/content/react-challenges.ts

Title :
Issue No. :
Code Stack : 

Added A calculator project

---

apps/vue/src/challenges/stopwatch/index.vue
apps/vue/src/routes.ts
shared/data/content/contributors.ts
shared/data/content/vue-challenges.ts

Title : Stopwatch with Vuejs
Issue No. : #370 
Code Stack : Vuejs
Close #370

[Vue] Basic stopwatch app with Vuejs

---

apps/react/src/challenges/transfer-list/Components/Buttons/Buttons.jsx
apps/react/src/challenges/transfer-list/Components/ListContainer/ListContainer.jsx
apps/react/src/challenges/transfer-list/Components/ListItems/ListItems.jsx
apps/react/src/challenges/transfer-list/MockData/transferListData.jsx
apps/react/src/challenges/transfer-list/TransferListApp.jsx
apps/react/src/challenges/transfer-list/TransferListApp.module.css
apps/react/src/pages/Challenge.tsx
shared/data/content/contributors.ts
shared/data/content/react-challenges.ts

Hi Sadanandpai,
I have created pull request for Transfer List, pls review and merge my PR.
Code Stack - React

Transfer List 

---

apps/vue/src/challenges/temprature-converter/index.vue
apps/vue/src/routes.ts
shared/data/content/vue-challenges.ts

Title : Added Temprature Coverter solution
Code Stack : Vue

[Vue] Add temperature converter solution

---

apps/react/package.json
apps/react/src/challenges/timeline/App.jsx
apps/react/src/challenges/timeline/data.jsx
apps/react/src/challenges/timeline/timeline.module.css
apps/react/src/pages/Challenge.tsx
package-lock.json
shared/data/content/contributors.ts
shared/data/content/react-challenges.ts

Added Timeline challenge in react challenges

React: Added Timeline challenge

---

apps/react/src/challenges/stepper/App.jsx
apps/react/src/challenges/stepper/App.module.css
apps/react/src/challenges/stepper/Stepper.jsx
apps/react/src/pages/Challenge.tsx
shared/data/content/contributors.ts
shared/data/content/react-challenges.ts

**Stepper Component Challenge**
- challenge category: React

Add STEPPER challenge

---

apps/host/src/components/modules/leaderboard/leaderboard.module.scss
apps/host/src/components/modules/leaderboard/leaderboard.tsx

Make leaderboard mobilefriendly

fix: leaderboard Responsive issue

---

apps/host/src/components/common/multi-select/multi-select.tsx
apps/host/src/components/modules/challenges/challenge-grid/challenge-grid.tsx
package-lock.json
package.json
shared/data/types/challenge.ts
shared/data/types/common.ts
shared/data/types/index.ts
shared/data/utils/challenges.helper.ts

Title :
Issue No. :
Code Stack : 

fix: search bar and contibutor dropdown added

---

apps/host/src/components/modules/challenges/challenge-grid/challenge-grid.module.scss
apps/host/src/components/modules/challenges/challenge-grid/challenge-grid.tsx

Title : [Challenges] Show no results when results are not found
Issue No. : https://github.com/sadanandpai/frontend-mini-challenges/issues/401

[Challenges] Show no results when results are not found

---

apps/host/src/components/modules/leaderboard/leaderboard.module.scss

Title : [Leaderboard] Bug in leaderboard
Issue No. : 389
Code Stack : 

Leaderboard Bug

---

apps/host/package.json
apps/host/setup.js
apps/host/src/helpers/leaderboard.test.ts
apps/host/src/helpers/leaderboard.ts
apps/host/vitest.config.ts
package-lock.json

Title : Added unit test in host app for helper functions
Issue No. : #412

Added unit test in host app for helper functions 

---

apps/vue/src/challenges/tic-tac-toe/helpers.ts
apps/vue/src/challenges/tic-tac-toe/index.vue
apps/vue/src/routes.ts
shared/data/content/vue-challenges.ts

Title: Addition of Tic Tac Toe
Code Stack: VueJS

Vue: Tic Tac Toe: Added new challenge

---

apps/react/src/challenges/15puzzle/AnimationDirection.ts
apps/react/src/challenges/15puzzle/App.tsx
apps/react/src/challenges/15puzzle/components/Board/board.module.css
apps/react/src/challenges/15puzzle/components/Board/index.tsx
apps/react/src/challenges/15puzzle/components/Tile/index.tsx
apps/react/src/challenges/15puzzle/components/Tile/tile.module.css
apps/react/src/pages/Challenge.tsx
shared/data/content/contributors.ts
shared/data/content/react-challenges.ts

Title : 15puzzle game
Issue No. : #394
Close #394

15puzzle game

---

apps/host/src/components/ThemeWrapper.tsx
apps/host/src/components/common/navbar/navbar.module.scss
apps/host/src/components/common/navbar/navbar.tsx
apps/host/src/components/modules/challenges/challenge-grid/challenge-grid.module.scss
apps/host/src/main.tsx
apps/host/src/styles.module.scss
package-lock.json
package.json
shared/styles/theme.css

#393 Add dark and light mode for the host application
Title: feat/ dark - light theme and toggle button
Issue No. : #393 
Code Stack: Js, CSS
Close #<393>
1. Using Lucid for icons instead of `Fontawesome` found it better.
2. Used Context for switching theme.
3. Example in a video.
https://github.com/sadanandpai/frontend-mini-challenges/assets/53713926/cf020e72-100f-404c-9d68-850d1c63468a

feat/#393 added dark-light theme toggle button

---

apps/host/src/components/common/navbar/navbar.module.scss
apps/host/src/components/common/navbar/navbar.tsx
package-lock.json
package.json

Title :Implemented hamburger menu for mobile view#399 
Issue No. :#399
Code Stack : React,Antd

Implemented hamburger menu for mobile view#399 

---

apps/host/src/components/ThemeWrapper.tsx

Title : Persist user theme selection
Issue No. : #420
Code Stack : host
Close #420

fix: persist theme selection

---

apps/host/src/components/modules/challenges/challenge-grid/challenge-filter.tsx
apps/host/src/components/modules/challenges/challenge-grid/challenge-grid.tsx
apps/host/src/styles.module.scss
shared/data/constants/difficulties.ts
shared/data/constants/index.ts
shared/data/package.json
shared/data/types/challenge.ts
shared/data/utils/challenges.helper.ts

Title: Add difficulties filter on the challenges screen
Issue No. : #387 
Code Stack: host
Close #387

fix(issue-387): add difficulty filter for challenges

---

apps/host/src/components/common/navbar/navbar.tsx

Title : Prop update in Antd Drawer Component
Issue No. : #431 
Close #431 

Prop update in Antd Drawer Component

---

apps/host/package.json
apps/host/src/components/modules/challenges/challenge-grid/challenge-grid.tsx
apps/host/src/components/modules/home/contribution/contribution.module.scss
apps/host/src/components/modules/home/contribution/contribution.tsx
package-lock.json

Title : migrating existing host animations to framer motion
Issue No. : #429 
Code Stack : React, JS
Close #429 
https://github.com/sadanandpai/frontend-mini-challenges/assets/53713926/5a3948d0-f7e9-42a6-8cc8-3fa10589ff04

#429[RFR] migrating existing animations to framer motion

---

apps/react/src/challenges/feedback-modal/App.jsx
apps/react/src/challenges/feedback-modal/components/FeedbackModal.jsx
apps/react/src/challenges/feedback-modal/components/RatingContent.jsx
apps/react/src/challenges/feedback-modal/data/emojicontent.js
apps/react/src/challenges/feedback-modal/styles.module.css
apps/react/src/challenges/feedback-modal/utilities/ClassUtility.js
apps/react/src/pages/Challenge.tsx
shared/data/content/contributors.ts
shared/data/content/react-challenges.ts

Title : Feedback Modal
Desktop
Responsive
Issue No. :
Code Stack : 

Feedback Modal | New Challenge | React

---

apps/host/src/components/modules/home/footer/footer.tsx

The footer had static current year 2023 which I made dynamic.  The current year is dynamic now.

make footer current year dynamic

---

apps/host/src/components/common/multi-select/multi-select.tsx
package-lock.json

…mode in host app
Title : UI changes for filters of challenges in dark mode for host app
Issue No. : #449 
Code Stack : HTML, CSS, JS
Close #449 

UI changes for filters of challenges in dark mode for host app

---

apps/javascript/src/challenges/multi-typing/README.md
apps/javascript/src/challenges/multi-typing/index.html
apps/javascript/src/challenges/multi-typing/index.js
apps/javascript/src/challenges/multi-typing/style.css

Title : JS: Multi Typing - Add customizations
Issue No. : #453 
Code Stack : HTML, CSS and JS
Close #453

Multi typing enhancement

---

apps/javascript/src/challenges/dynamic-tooltip/index.css
apps/javascript/src/challenges/dynamic-tooltip/index.html
apps/javascript/src/challenges/dynamic-tooltip/index.js
shared/data/content/js-challenges.ts

Title : Dynamic Tooltip [LinkedIn Interview Question]
Issue No. : 1
Code Stack : Vanilla JS, HTML, CSS

Dynamic Tooltip [LinkedIn Interview Question]

---

shared/data/utils/challenges.helper.ts

Title : All filter not working with the rest of the filters fix
Issue No. :
Code Stack : HTML, CSS, Javascript
[rest of the filters working fix for all filters.webm](https://github.com/user-attachments/assets/82cf7d4c-3f6a-4853-80b7-e27e332b0cb0)

fixed the rest of the filters not working with all filter

---

apps/host/src/components/common/checkbox/checkbox.tsx
apps/host/src/components/modules/challenges/challenge-grid/challenge-filter.tsx
apps/host/src/components/modules/challenges/challenge-grid/challenge-grid.module.scss
apps/host/src/components/modules/challenges/challenge-grid/challenge-grid.tsx
package-lock.json
shared/data/types/challenge.ts
shared/data/utils/challenges.helper.ts

Title : New challenge filter enchancement added for host app
Issue No. : #400 
Code Stack : HTML, CSS, Javascript
Close #400 

new challenge filter enchancement added for host app

---

apps/host/src/components/modules/challenges/challenge-grid/challenge-grid.module.scss

Title :  fixed visibility of tags filter in dark mode
Issue No. :  #468 
Code Stack : 
Close #468 

#468 improved visibility of filter in dark mode

---

apps/host/src/components/modules/challenges/challenge-grid/challenge-grid.module.scss

Title : fixed the dark mode color to blue
Issue No. : #468 
Code Stack : CSS

#468 fixed the dark mode color to blue

---

apps/javascript/src/challenges/weather-app/index.html
apps/javascript/src/challenges/weather-app/index.js

Title :
Issue No. : #475 
Code Stack : Javascript
Close #<475>

Added  the weather search on key press function.

---

apps/react/src/challenges/nested-checkbox/App.jsx
apps/react/src/challenges/nested-checkbox/CheckBox.jsx
apps/react/src/challenges/nested-checkbox/CheckBoxList.jsx
apps/react/src/challenges/nested-checkbox/constants.js
apps/react/src/challenges/nested-checkbox/styles.module.css
apps/react/src/pages/Challenge.tsx
shared/data/content/contributors.ts
shared/data/content/react-challenges.ts

Title : React: Nested Checkbox: Added new challenge
Issue No. :
Code Stack : React.js

React: Nested Checkbox: Added new challenge

---

apps/javascript/src/challenges/dice-game/README.md
apps/react/src/challenges/stepper/App.module.css
apps/react/src/challenges/stepper/Stepper.jsx

Title : React: Stepper - Enhance the features
Issue No. : #483
Code Stack : REACT
Close #483

added enhancement in stepper project

---

apps/host/src/components/common/multi-select/multi-select.tsx

Title : Fixed Issue-488
Issue No. : #488
Close #488 

fixed css bug #488

---

apps/react/src/pages/Challenge.tsx
shared/data/content/react-challenges.ts

Title: Fixed Broken Link
Issue No. : 491 (Broken Link for React Challenge Guess the Number #491)
Close #491

fixed bug #491

---

apps/host/src/components/common/multi-select/multi-select.tsx
apps/host/src/components/modules/challenges/challenge-grid/challenge-filter.tsx

Title : Dropdowns should have a more descriptive placeholder text
Issue No. : 494
Close #494 

Fixed #494: Added descriptive placeholder text for Select dropdown

---

apps/javascript/src/challenges/column-table/index.html
apps/javascript/src/challenges/column-table/index.js

Title :  improve ux for columns table component
Issue No. : 502
Code Stack :  Javascript and CSS
Close #502

502 : UX - Columns Table Challenge

---

apps/javascript/src/challenges/password-strength/style.css
apps/react/src/challenges/password-strength/passwordStrength.module.scss

Title : Fix: Align Progress Bar Edges with Parent Container in Password Strength Indicator
Issue No. : #505
Code Stack : HTML, CSS, JS
Close #505

Fix #505: Align Progress Bar Edges with Parent Container in Password Strength Indicator

---

apps/react/src/challenges/stopwatch/App.jsx

React Stopwatch component enhancement
Title : Fixed pause and start value related bugs in react-challenges-stopwatch

Fixed pause and start value related bugs in react-challenges-stopwatch

---

apps/host/src/components/modules/home/features/features.module.scss

✅ Added a scaling effect to the article section to enhance the look and feel.  
> 📸 *Screenshot added for reference.*  
https://github.com/user-attachments/assets/26cd7db4-ac49-4127-877a-4d3703d88ce5

Added scaling effect to make the look and feel much better in the UI

---

apps/css/src/helpers/navbar.ts
apps/host/src/components/modules/challenges/challenge-grid/challenge-grid.tsx
apps/host/src/helpers/leaderboard.test.ts
apps/javascript/src/helpers/navbar.ts
apps/react/src/components/challenge-navbar/ChallengeNavbar.tsx
apps/react/src/pages/Challenge.tsx
apps/vue/src/components/Navbar.vue
apps/vue/src/pages/challenge.vue
shared/components/index.ts
shared/components/modal/modal.html
shared/components/modal/modal.scss
shared/components/modal/modal.ts
shared/components/navbar/navbar.html
shared/components/navbar/navbar.scss
shared/data/content/css-challenges.ts
shared/data/content/js-challenges.ts
shared/data/content/ng-challenges.ts
shared/data/content/react-challenges.ts
shared/data/content/vue-challenges.ts
shared/data/types/challenge.ts

Title : Component to display the question for each challenge
Issue No. : #490 
Code Stack : Typescript
Close #490 
https://github.com/user-attachments/assets/d7663d5b-c56d-43d6-8dbd-21976b42a67d

feat: [issue-490] add question dialog web component for challenge descriptions

---

apps/host/src/components/common/navbar/navbar.tsx

> Replacing the anchor tag with the Link tag, as the anchor tag refreshes the entire page, whereas Link does not, for the Link tag helps increase the page performance as it does not refresh the whole page.
https://github.com/user-attachments/assets/82953acd-5194-41fa-8a54-5a84293bc294

Replaced anchor tag with Link tag
